"""Initial migration

Revision ID: bfa885b8fdae
Revises: 
Create Date: 2024-05-08 17:17:46.026054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa885b8fdae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
